import './globals.css'
import { Poppins, Merienda } from 'next/font/google'
import 'remixicon/fonts/remixicon.css'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import Head from 'next/head'

const navLinks=[
  {
    path:'/',
    display:'Home'
  },
  {
    path:'#services',
    display:'Services',
  },
  {
    path:'#about',
    display:'About',
  },
  {
    path:'#projects',
    display:'Projects',
  },
  {
    path:'#contact',
    display:'Contact',
  },
]

const socialLinks = {
  linkedin: process.env.Linkedin,
  github: process.env.Github,
  twitter: process.env.Twitter,
};

const pop = Poppins({ subsets: ['latin'], display:'swap',weight:['300','400'], variable:'--font-pop' })
const merienda= Merienda({subsets:['latin'], display:'swap',weight:'800', variable:'--font-merienda'})


export const metadata = {
  title: "Maria Trinidad",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${pop.variable} ${merienda.variable}`}>
      <Head>
      <meta name='viewport' content='width-device-width, initial-scale=1'/>
      <link rel='icon' href='./favicon.ico'/>
      </Head>
      <main className={`${pop.variable} font-pop w-full h-full`}>
      <Header navLinks={navLinks}/>
      <div >{children}</div>
      <Footer navLinks={navLinks} socialLinks={socialLinks}/>
      </main>
    </html>
  )
}
