import './globals.css'
import { Poppins, Merienda } from 'next/font/google'
import 'remixicon/fonts/remixicon.css'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import Providers from './components/darkMode/Providers'
import navLinks from './components/data/navLinks'

const socialLinks = {
  linkedin: process.env.Linkedin,
  github: process.env.Github,
  twitter: process.env.Twitter,
};

const pop = Poppins({ subsets: ['latin'], display:'swap',weight:['300','400'], variable:'--font-pop' })
const merienda= Merienda({subsets:['latin'], display:'swap',weight:'800', variable:'--font-merienda'})


export const metadata = {
  title: "Maria Trinidad",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${pop.variable} ${merienda.variable}`}>
      <body className={`${pop.variable} font-pop w-full h-full dark:bg-dark-bg dark:text-dark-text`}>
      <Header navLinks={navLinks}/>
      <Providers >{children}</Providers>
      <Footer navLinks={navLinks} socialLinks={socialLinks}/>
      </body>
    </html>
  )
}
